version: "2.1"
services:
  app:
    build: ./API/ 
    environment:
      user: root
      passwd: root
      port: 3306
      host: localhost
      db: Statistics
    depends_on:
      db:
        condition: service_healthy
    network_mode: "host"
    restart: always
     
  db:
    build: ./Database/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
